Dashboard/urls.py
from . import views
from django.conf.urls import url
from django.urls import path, include
app_name = 'Dashboard'


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('shirt', views.shirt, name='shirt'),
    path('shoes', views.shoes, name='shoes'),
    path('shorts', views.shorts, name='shorts'),
    path('jeans', views.jeans, name='jeans'),
    path('red', views.red, name='red'),
    path('blue', views.blue, name='blue'),
    path('yellow', views.yellow, name='yellow'),
    path('black', views.black, name='black'),
    path('green', views.green, name='green'),
    path('white', views.white, name='white'),
    path('sugessions', views.suggesions, name='sugessions'),
]

ImageRecognition/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'search'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', views.home, name='home'),
    path('limeroad', views.limeroad, name='limeroad'),
    path('zobello', views.zobello, name='zobello'),
    path('randomize', views.randomize, name='randomize'),
    path('', views.landing, name="landing"),
    path('trending', views.trending, name="trending"),
    path('search-bewakoof', views.search_bewakoof, name="search-bewakoof"),
    path('search-limeroad', views.search_limeroad, name="search-limeroad"),
    path('search-zobello', views.search_zobello, name="search-zobello"),
    path('search-random', views.search_random, name="search-random"),
    path('trend/<int:pk>/', views.trend, name="trend"),
]

ImageSocial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ImageRecognition.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include('Dashboard.urls')),
]

accounts/urls.py
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.urls import path, include


app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name ='logout'),
    path('signup/', views.SignUp, name='signup')
]

ImageRecognition/models.py
from django.db import models
from django.contrib.auth.models import User


class Search(models.Model):
    search_term = models.CharField(max_length=100)
    users = models.ManyToManyField(User)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.search_term


ImageRecognition/forms.py
from django import forms

class UploadFileForm(forms.Form):
	image = forms.ImageField()

class GetSearch(forms.Form):
	search = forms.CharField(max_length=100)

ImageRecognition/views.py

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from . import forms
from .models import Search
from django.db.models import Count

# Imaginary function to handle an uploaded file.
from .operations import recognize, scrape, scrape_limeroad, scrape_zobello
from .color_detection import detect_color

search_global = ''

def home(request):
    global search_global
    output = search_global
    search_term = output
    listings = scrape(search_term)
    if len(listings) == 0:
        search_term = search_term.split(' ')[0]
        listings = scrape(search_term.split(' ')[0])
    context = {'search': search_term,
                'listings': listings}
    if request.method == 'POST':
        form = forms.UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            output = recognize(request.FILES['image'])
            if 'trunk' in output or 'shorts' in output or 'mini' in output:
                output = 'shorts'
            elif 'shoe' in output:
                output = 'shoe'
            elif 'jersey' in output:
                output = 'tee'
            elif 'cardigan' in output: 
                output = 'shirt'
            elif 'lorikeet' in output or 'macaw' in output:
                output = 'parrot'
            to_search = output.split('_')
            search_term = ''
            for i in to_search:
                search_term += i
            color_term = detect_color(request.FILES['image'])
            search_term += " " + color_term
            if request.user.is_active:
                search_term = request.user.customer.gender + ' ' + search_term
            search_global = search_term
            listings = scrape(search_term)
            if len(listings) == 0:
                search_term = color_term
                listings = scrape(color_term)

            if request.user.is_active and search_term != '':
                s, created = Search.objects.get_or_create(search_term=search_term)
                s.users.add(request.user)

            context = {'form': form, 'output': output,
                        'listings': listings,
                        'search': search_term}
            return render(request, 'search.html', context)
    else:
        form = forms.UploadFileForm()
        context['form'] = form
    return render(request, 'search.html', context)


def limeroad(request):
    global search_global
    output = search_global
    search_term = output
    listings = scrape_limeroad(search_term)
    if len(listings) == 0:
        search_term = search_term.split(' ')[0]
        listings = scrape_limeroad(search_term.split(' ')[0])
    context = {'search': search_term,
                'listings': listings}
    if request.method == 'POST':
        form = forms.UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            output = recognize(request.FILES['image'])
            if 'trunk' in output or 'shorts' in output or 'mini' in output:
                output = 'shorts'
            elif 'shoe' in output:
                output = 'shoe'
            elif 'jersey' in output:
                output = 'tee'
            elif 'cardigan' in output:
                output = 'shirt'
            elif 'lorikeet' in output or 'macaw' in output:
                output = 'parrot'
            to_search = output.split('_')
            search_term = ''
            for i in to_search:
                search_term += i
            color_term = detect_color(request.FILES['image'])
            search_term += " " + color_term
            if request.user.is_active:
                search_term = request.user.customer.gender + ' ' + search_term
            search_global = search_term
            listings = scrape_limeroad(search_term)
            if len(listings) == 0:
                search_term = color_term
                listings = scrape_limeroad(color_term)

            if request.user.is_active and search_term != '':
                s, created = Search.objects.get_or_create(search_term=search_term)
                s.users.add(request.user)

            context = {'form': form, 'output': output,
                        'listings': listings,
                        'search': search_term}
            return render(request, 'search.html', context)
    else:
        form = forms.UploadFileForm()
        context['form'] = form
    return render(request, 'search.html', context)

def zobello(request):
    global search_global
    output = search_global
    search_term = output
    listings = scrape_zobello(search_term)
    if len(listings) == 0:
        search_term = search_term.split(' ')[0]
        listings = scrape(search_term.split(' ')[0])
    context = {'search': search_term,
                'listings': listings}
    if request.method == 'POST':
        form = forms.UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            output = recognize(request.FILES['image'])
            if 'trunk' in output or 'shorts' in output or 'mini' in output:
                output = 'shorts'
            elif 'shoe' in output:
                output = 'shoe'
            elif 'jersey' in output:
                output = 'tee'
            elif 'cardigan' in output:
                output = 'shirt'
            elif 'lorikeet' in output or 'macaw' in output:
                output = 'parrot'
            to_search = output.split('_')
            search_term = ''
            for i in to_search:
                search_term += i
            color_term = detect_color(request.FILES['image'])
            search_term += " " + color_term
            if request.user.is_active:
                search_term = request.user.customer.gender + ' ' + search_term
            search_global = search_term
            listings = scrape_zobello(search_term)
            if len(listings) == 0:
                search_term = color_term
                listings = scrape_zobello(color_term)

            if request.user.is_active and search_term != '':
                s, created = Search.objects.get_or_create(search_term=search_term)
                s.users.add(request.user)


            context = {'form': form, 'output': output,
                        'listings': listings,
                        'search': search_term}
            return render(request, 'search.html', context)
    else:
        form = forms.UploadFileForm()
        context['form'] = form
    return render(request, 'search.html', context)


def randomize(request):
    global search_global
    output = search_global
    search_term = output
    listings_zob = scrape_zobello(search_term)
    listings_lime = scrape_limeroad(search_term)
    listings_bewa = scrape(search_term)
    if output == 'jean' or output=='jersey':
        listings = listings_lime[:5] + listings_bewa[:5]
    else:
        listings = listings_lime[:5] + listings_zob[:5]
    context = {'search': search_term,
                'listings': listings}
    if request.method == 'POST':
        form = forms.UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            output = recognize(request.FILES['image'])
            if 'trunk' in output or 'shorts' in output or 'mini' in output:
                output = 'shorts'
            elif 'shoe' in output:
                output = 'shoe'
            elif 'jersey' in output:
                output = 'tee'
            elif 'cardigan' in output:
                output = 'shirt'
            elif 'lorikeet' in output or 'macaw' in output:
                output = 'parrot'
            to_search = output.split('_')
            search_term = ''
            for i in to_search:
                search_term += i
            search_term += " " + detect_color(request.FILES['image'])
            if request.user.is_active:
                search_term = request.user.customer.gender + ' ' + search_term
            search_global = search_term

            if request.user.is_active and search_term != '':
                s, created = Search.objects.get_or_create(search_term=search_term)
                s.users.add(request.user)

            listings_zob = scrape_zobello(search_term)
            listings_lime = scrape_limeroad(search_term)
            listings_bewa = scrape(search_term)
            if output == 'jeans' or output == 'jean' or output=='jersey':
                listings = listings_lime[:5] + listings_bewa[:5]
            else:
                listings = listings_lime[:5] + listings_zob[:5]
            context = {'form': form, 'output': output,
                        'listings': listings,
                        'search': search_term}
            return render(request, 'search.html', context)
    else:
        form = forms.UploadFileForm()
        context['form'] = form
    return render(request, 'search.html', context)


def landing(request):
    return render(request, 'landing.html')


def trending(request):
    search_list = Search.objects.annotate(user_count=Count('users')).order_by('-user_count')

    
    context = {
        'search_list': search_list,
    }

    return render(request, 'trending.html', context)


#####################################################################################
############################ Search Term ############################################
#####################################################################################

def search_bewakoof(request):
    global search_global
    output = search_global
    search_term = output
    listings = scrape(search_term)
    if len(listings) == 0:
        search_term = search_term.split(' ')[0]
        listings = scrape(search_term.split(' ')[0])
    context = {'search': search_term,

ImageRecognition/templates/base1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">

    <title>Apna Dhukaan</title>

    <style>
        .trending-field {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            align-items: baseline;
            margin: 10px;
        }
      
        .rank {
            font-size: 25px;
            margin: 10px 30px;
        }
      
        .trending-card {
            padding: 10px 20px;
            border: 0.5px solid #000000;
            border-radius: 9px;
        }
      
        .trending-card a {
            color: #2c2c2c;
        }
      
        .trending-card a:hover {
            background-color: #000000;
            color: #000000;
            font-weight: 700;
            text-decoration: none;
        }
      
        .trending-list {
            display: flex;
            width: 80vw;
            justify-content: space-evenly;
            flex-wrap: wrap;
            margin: 10px auto;
        }
    </style>
</head>

<body>

    <nav id="navbar" class="navbar custom-light navbar-expand-lg transparent navbar-inverse">

        <a class="navbar-brand ml-auto" href="{% url 'search:landing' %}">Apna Dhukaan</a>

        <button class="navbar-toggler navbar-light ml-auto" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
            aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'search:landing'%}">Home</a>
                </li>
                <li class="nav-item current">
                    <a class="nav-link" href="{%url 'search:home'%}">Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'search:trending'%}">Trending</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'search:search-bewakoof' %}">Search By Term</a>
                </li>
            </ul>


        {% if user.is_authenticated %}
            <a href="{% url 'Dashboard:dashboard' %}" class="btn btn-primary glow-button" style="color: white">Dashboard</a>
        {% else %}
            <a href="{% url 'accounts:login' %}" class="btn btn-primary glow-button" style="color: white">Login</a>
        {% endif %}

    </nav>

    {% block content %}

    {% endblock %}

    <!-- <script src="staticfiles/js/app.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>

ImageRecognition/templates/landing.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        section .wave{
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
            height: 100px;
            background: url("{% static 'img/wave.png' %}");
            background-size: 1000px 100px;
        }
    </style>

    <title>Apna Dhukaan</title>
</head>

<body>

    <nav id="navbar-landing" class="navbar custom-dark navbar-expand-lg transparent navbar-inverse lnavbar">

        <a class="navbar-brand ml-auto" href="{%url 'search:landing'%}">Apna Dhukaan</a>

        <button class="navbar-toggler navbar-light ml-auto" type="button" data-toggle="collapse"
            data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item current">
                    <a class="nav-link" href="{%url 'search:landing'%}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'search:home' %}">Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'search:trending' %}">Trending</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'search:search-bewakoof' %}">Term Search</a>
                </li>
            </ul>
            {% if user.is_authenticated %}
                <a href="{% url 'Dashboard:dashboard' %}" type="button" class="btn btn-primary glow-button ml-auto">Profile</a>
            {% else %}
            <a href="{% url 'accounts:login' %}" type="button" class="btn btn-secondary glow-button ml-auto">Login</a>
            {% endif %}
        </div>


    </nav>

    <section>
        <div class="primary-description header">
            Spend less time searching
        </div>
        <div class="secondary-description transparent-header">
            <p>Connect with us and get personalised recommendations</p>
        </div>

        <div class="btn-wrapper">
            <a class="btn light-button glow-light-button" href="{% url 'search:home' %}">
                Get Started
            </a>
            <a class="btn light-button-2" href="{%url 'accounts:signup'%}">
                Sign Up
            </a>
        </div>



        <div class="wave wave1"></div>
        <div class="wave wave2"></div>
        <div class="wave wave3"></div>
        <div class="wave wave4"></div>
    </section>


    <!-- <div class="wrapper">

        <div class="grid">
            <div class="grid-element">
                <ion-icon name="camera-reverse-outline" size="large"></ion-icon>
                <h5 class="grid-primary">
                    Reverse Image Search
                </h5>
                <p class="grid-secondary">Search for products using their pictures</p>
            </div>
            <div class="grid-element">
                <ion-icon name="person-outline" size="large"></ion-icon>
                <h5 class="grid-primary">
                    Recommendations
                </h5>
                <p class="grid-secondary">Search for products using their pictures</p>
            </div>
            <div class="grid-element">
                <ion-icon name="trending-up-outline" size="large"></ion-icon>
                <h5 class="grid-primary">
                    Top Trending Items
                </h5>
                <p class="grid-secondary">Search for products using their pictures</p>
            </div>
        </div>
    </div> -->

    <div class="wrapper">
        <div class="primary-description">
            More than just a tool
        </div>
        <div class="secondary-description">
            Explore what else we can do for you
        </div>
        <div class="container">
            <div class="feature col-md-6 red">
                <span class="circle">
                    <ion-icon name="camera-reverse-outline" size="large"></ion-icon>
                </span>
                <h3>Reverse Image Search</h3>
                <p>Search for products using their pictures. Apna Dhukaan uses multiple models for object detection and colour detection for better search results.</p>
            </div>
            <div class="feature col-md-6 blue">
                <span class="circle">
                    <ion-icon name="person-outline" size="large"></ion-icon>
                </span>
                <h3>Personalised Recommendations</h3>
                <p>Get recommendations based on your favourite colour, clothing and search results.</p>
            </div>
            <div class="feature col-md-6 yellow">
                <span class="circle">
                    <ion-icon name="trending-up-outline" size="large"></ion-icon>
                </span>
                <h3>Top Trending Products</h3>
                <p>Never miss out on the latest fashion trends!</p>
            </div>
            <div class="feature col-md-6 green">
                <span class="circle">
                    <ion-icon name="time-outline" size="large"></ion-icon>
                </span>
                <h3>Save Time</h3>
                <p>Less time spent on searching means more time to spend on other things.</p>
            </div>
        </div>
    </div>

    <div class="wrapper">
        <div class="primary-description">
            Products from best online stores
        </div>
        <div class="secondary-description">
            Never compromise on quality products
        </div>

        <div class="container">
            <a href="{% url 'search:search-bewakoof' %}"><img src="{% static '/img/bewakoof-logo.png' %}" alt="" height="90"></a>
            <a href="{% url 'search:search-limeroad' %}"><img src="{% static '/img/limeroad-logo.jpg' %}" alt="" height="120"></a>
            <a href="{% url 'search:search-zobello' %}"><img src="{% static '/img/zobello-logo.png' %}" alt="" height="80"></a>
            <!-- <a href="{% url 'search:search-random' %}"><img src="{% static '/img/koovs-logo.png' %}" alt="" height="40"></a> -->
        </div>
    </div>

    <!-- <div class="wrapper" style="background-color: #000000; clip-path: polygon(0% 20%, 100% 0%, 100% 80%, 0% 100%);">
        <div class="container-2">
            <h4 class="white-description">Start searching!</h4>
            <button class="btn light-button glow-light-button">
                Get Started
            </button>
        </div>
    </div> -->

    <!-- <footer class="footer-distributed">

        <div class="footer-left">

            <h3>Product<span>Social</span></h3>

            <p class="footer-links">
                <a href="#">Home</a>
                ·
                <a href="#">Search</a>
                ·
                <a href="#">Trending</a>
                ·
                <a href="#">Search by term</a>
            </p>

            <p class="footer-company-name">Apna Dhukaan &copy; 2020</p>
        </div>

        <div class="footer-center">

            <div>
                <i class="fa fa-map-marker"></i>
                <p><span>Zoom Call</span> Mumbai, India</p>
            </div>

            <div>
                <i class="fa fa-phone"></i>
                <p>+1 555 123456</p>
            </div>

            <div>
                <i class="fa fa-envelope"></i>
                <p><a href="mailto:support@company.com">contact@apnadukaan.com</a></p>
            </div>

        </div>

        <div class="footer-right">

            <p class="footer-company-about">
                <span>About the company</span>
                Apna Dhukaan helps you search your clothing items byt using their photos and get personalised recommendations so that you spend less time looking for stuff!
            </p>

            <div class="footer-icons">

                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-linkedin"></i></a>
                <a href="#"><i class="fa fa-github"></i></a>

            </div>

        </div>

    </footer> -->

    <script type="text/javascript">

        /* Sticky Navbar */
        var nav = document.getElementById("navbar");
        var landing = document.getElementById("navbar-landing");
        var sticky;
        if (nav != null) sticky = nav.offsetTop;
        else sticky = landing.offsetTop;


        window.onscroll = () => {
            if (window.pageYOffset > sticky) {
                if (nav != null) nav.classList.add("sticky");
                else {
                    landing.classList.add("sticky");
                    landing.classList.add("custom-light");
                    landing.classList.remove("custom-dark");
                }
            }
            else {
                if (nav != null) nav.classList.remove("sticky");
                else {
                    landing.classList.remove("sticky");
                    landing.classList.add("custom-dark");
                    landing.classList.remove("custom-light");
                }
            }
        };

        /* Login Signup */
        function gotoSignUp() {
            document.getElementById("sign-up").style.display = "inline";
            document.getElementById("login").style.display = "none";
        }

        function gotoLogin() {
            document.getElementById("sign-up").style.display = "none";
            document.getElementById("login").style.display = "inline";
        }


    /* Sticky Navbar */
    var nav = document.getElementById("navbar");
    var landing = document.getElementById("navbar-landing");
    var sticky;
    if(nav != null) sticky = nav.offsetTop;
    else sticky = landing.offsetTop;


    window.onscroll = () => {
        if (window.pageYOffset > sticky) {
            if(nav != null) nav.classList.add("sticky");
            else {
                landing.classList.add("sticky");
                landing.classList.add("custom-light");
                landing.classList.remove("custom-dark");
            }
        }
        else {
            if(nav != null) nav.classList.remove("sticky");
            else {
                landing.classList.remove("sticky");
                landing.classList.add("custom-dark");
                landing.classList.remove("custom-light");
            }
        }
    };

    /* Login Signup */
    function gotoSignUp() {
        document.getElementById("sign-up").style.display = "inline";
        document.getElementById("login").style.display = "none";
    }

    function gotoLogin() {
        document.getElementById("sign-up").style.display = "none";
        document.getElementById("login").style.display = "inline";
    }


    </script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
    <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
</body>

</html>

ImageRecognition/templates/search-term.html
{% extends 'base1.html' %}

{% load static %}


{% block content  %}
    <div class="container">
        <div class="description">
            <div class="row primary-description col-md">
                Spend Less Time Searching!
            </div>
            <div class="row secondary-description col-md ml-5">
                Best Deals across multiple websites
            </div>
            <form method="post">
                <div class="custom-file">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary glow-button upload"> Search </button>
            </form>
        </div>
    </div>
    <h2 class="text-center">{{ search | title }}</h2>
    <div class="products-found">
        <div class="container">
            <a href="{% url 'search:search-bewakoof' %}"><img src="{% static '/img/bewakoof-logo.png' %}" alt="" height="90"></a>
            <a href="{% url 'search:search-limeroad' %}"><img src="{% static '/img/limeroad-logo.jpg' %}" alt="" height="120"></a>
            <a href="{% url 'search:search-zobello' %}"><img src="{% static '/img/zobello-logo.png' %}" alt="" height="80"></a>
            <!-- <a href="{% url 'search:search-random' %}"><img src="{% static '/img/image_placeholder.jpg' %}" alt="" height="40"></a> -->
        </div>
        {% if listings %}
        <div class="container products-found">
            <!-- Insert product cards here! -->
            {% for post in listings %}
            <div class="card" style="width: 18rem">
                <img src="{{ post.2 }}" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{ post.0 }}</h5>
                    <div class="container">
                        <h5>{{ post.1 }}</h5>
                        <a href="{{ post.3 }}" class="btn btn-primary glow-button" target="_blank">Visit Store</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>

{% endblock %}