Dashboard/urls.py
from . import views
from django.conf.urls import url
from django.urls import path, include
app_name = 'Dashboard'


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('shirt', views.shirt, name='shirt'),
    path('shoes', views.shoes, name='shoes'),
    path('shorts', views.shorts, name='shorts'),
    path('jeans', views.jeans, name='jeans'),
    path('red', views.red, name='red'),
    path('blue', views.blue, name='blue'),
    path('yellow', views.yellow, name='yellow'),
    path('black', views.black, name='black'),
    path('green', views.green, name='green'),
    path('white', views.white, name='white'),
    path('sugessions', views.suggesions, name='sugessions'),
]

ImageRecognition/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'search'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home', views.home, name='home'),
    path('limeroad', views.limeroad, name='limeroad'),
    path('zobello', views.zobello, name='zobello'),
    path('randomize', views.randomize, name='randomize'),
    path('', views.landing, name="landing"),
    path('trending', views.trending, name="trending"),
    path('search-bewakoof', views.search_bewakoof, name="search-bewakoof"),
    path('search-limeroad', views.search_limeroad, name="search-limeroad"),
    path('search-zobello', views.search_zobello, name="search-zobello"),
    path('search-random', views.search_random, name="search-random"),
    path('trend/<int:pk>/', views.trend, name="trend"),
]

ImageSocial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ImageRecognition.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include('Dashboard.urls')),
]

accounts/urls.py
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.urls import path, include


app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name ='logout'),
    path('signup/', views.SignUp, name='signup')
]

Dashboard/models.py
from django.db import models

# Create your models here.

Dashboard/views.py
from django.shortcuts import render
from .operations import scrape, scrape_limeroad, scrape_zobello
from django.contrib.auth.models import User
from accounts.models import Customer
# Create your views here.

def dashboard(request):

    search_terms = []
    search_now = ''
    search_now1 = ''
    search_now2 = ''
    search_now3 = ''
    listings1 = []
    listings2 = []
    listings3 = []
    if request.user.is_active:
        search_terms = request.user.search_set.all()
        print(search_terms)
        if search_terms:
            search_now = search_terms[len(search_terms) - 1].search_term
            if 'tee' in search_now.lower():
                listings1 = scrape(search_now)
            else:
                listings1 = scrape_limeroad(search_now)
            search_now1 = search_now
            if len(search_terms) - 2 >= 0:
                search_now = search_terms[len(search_terms) - 2].search_term
                if 'tee' in search_now.lower():
                    listings2 = scrape(search_now)
                else:
                    listings2 = scrape_limeroad(search_now)
                search_now2 = search_now
            elif len(search_terms) - 3 >= 0:
                search_now = search_terms[len(search_terms) - 3].search_term
                if 'tee' in search_now.lower():
                    listings3 = scrape(search_now)
                else:
                    listings3 = scrape_limeroad(search_now)
                search_now3 = search_now
            if len(search_terms) >= 3:
                listings1 = listings1[:3]
                listings2 = listings2[:3]
                listings3 = listings3[:3]
            elif len(search_terms) >= 2:
                listings1 = listings1[:6]
                listings2 = listings2[:6]
        else:
            listings1 = []
            listings2 = []
            listings3 = []
    else:
        listings1 = []
        listings2 = []
        listings3 = []

    context = {
        'listings1': listings1,
        'listings2': listings2,
        'listings3': listings3,
        'search1': search_now1,
        'search2': search_now2,
        'search3': search_now3,
    }

    return render(request, 'dashboard-recent.html', context)


def shirt(request):

    search_term = ''
    if request.user.is_active:
        customer = request.user.customer
        search_color = customer.favourite_color
        search_prod = 'shirt'
        search_term = request.user.customer.gender + ' ' + search_color + " " + search_prod
        print(search_term)
        listings = scrape(search_term)
        listings += scrape_limeroad(search_term)
        listings += scrape_zobello(search_term)
    else:
        listings = []

    context = {
        'listings': listings,
        'search': search_term,
    }

    return render(request, 'dashboard-product.html', context)

def shoes(request):

    search_term = ''
    if request.user.is_active:
        customer = request.user.customer
        search_color = customer.favourite_color
        search_prod = 'shoes'
        search_term = search_color + " " + search_prod
        search_term = request.user.customer.gender + ' ' + search_color + " " + search_prod
        print(search_term)
        listings = scrape_limeroad(search_term)
        listings += scrape_zobello(search_term)
        listings += scrape(search_term)
    else:
        listings = []

    context = {
        'listings': listings,
        'search': search_term,
    }

    return render(request, 'dashboard-product.html', context)

def shorts(request):

    search_term = ''
    if request.user.is_active:
        customer = request.user.customer
        search_color = customer.favourite_color
        search_prod = 'shorts'
        search_term = search_color + " " + search_prod
        search_term = request.user.customer.gender + ' ' + search_color + " " + search_prod
        print(search_term)
        listings = scrape_limeroad(search_term)
        listings += scrape_zobello(search_term)
        listings += scrape(search_term)
    else:
        listings = []

    context = {
        'listings': listings,
        'search': search_term,
    }

    return render(request, 'dashboard-product.html', context)

def jeans(request):
    search_prod = ''
    search_term = ''
    if request.user.is_active:
        customer = request.user.customer
        search_color = customer.favourite_color
        search_prod = 'jeans'
        search_term = search_color + " " + search_prod
        search_term = request.user.customer.gender + ' ' + search_color + " " + search_prod
        print(search_term)
        listings = scrape_limeroad(search_term)
        listings += scrape_zobello(search_term)
        listings += scrape(search_term)
    else:
        listings = []

    context = {
        'listings': listings,
        'search': search_term,
    }

    return render(request, 'dashboard-product.html', context)

###########################################################

def blue(request):
    search_prod = ''
    search_term = ''
    if request.user.is_active:
        customer = request.user.customer
        search_color = 'blue'
        search_prod = customer.favourite_item
        search_term = search_color + " " + search_prod
        search_term = request.user.customer.gender + ' ' + search_color + " " + search_prod
        print(search_prod)
        if request.user.customer.gender == 'male':
            listings = scrape(search_term)
            listings += scrape_zobello(search_term)
            listings += scrape_limeroad(search_term)
        else:
            listings = scrape_limeroad(search_term)
            listings += scrape_zobello(search_term)
            listings += scrape(search_term)
    else:
        listings = []

    context = {
        'listings': listings,
        'search': search_prod,
    }

    return render(request, 'dashboard.html', context)

def red(request):
    search_prod = ''
    search_term = ''
    if request.user.is_active:
        customer = request.user.customer
        search_color = 'red'
        search_prod = customer.favourite_item
        search_term = search_color + " " + search_prod
        search_term = request.user.customer.gender + ' ' + search_color + " " + search_prod
        print(search_term)
        if request.user.customer.gender == 'male':
            listings = scrape(search_term)
            listings += scrape_zobello(search_term)
            listings += scrape_limeroad(search_term)
        else:
            listings = scrape_limeroad(search_term)
            listings += scrape_zobello(search_term)
            listings += scrape(search_term)
    else:
        listings = []

    context = {
        'listings': listings,
        'search': search_prod,
    }

    return render(request, 'dashboard.html', context)

def green(request):
    search_prod = ''
    search_term = ''
    if request.user.is_active:
        customer = request.user.customer
        search_color = 'green'
        search_prod = customer.favourite_item
        search_term = search_color + " " + search_prod
        search_term = request.user.customer.gender + ' ' + search_color + " " + search_prod
        print(search_term)
        if request.user.customer.gender == 'male':
            listings = scrape(search_term)
            listings += scrape_zobello(search_term)
            listings += scrape_limeroad(search_term)
        else:
            listings = scrape_limeroad(search_term)
            listings += scrape_zobello(search_term)
            listings += scrape(search_term)
    else:
        listings = []

    context = {
        'listings': listings,
        'search': search_prod,
    }

    return render(request, 'dashboard.html', context)

def black(request):
    search_prod = ''
    search_term = ''
    if request.user.is_active:
        customer = request.user.customer
        search_color = 'black'
        search_prod = customer.favourite_item
        search_term = search_color + " " + search_prod
        search_term = request.user.customer.gender + ' ' + search_color + " " + search_prod
        print(search_term)
        if request.user.customer.gender == 'male':
            listings = scrape(search_term)
            listings += scrape_zobello(search_term)
            listings += scrape_limeroad(search_term)
        else:
            listings = scrape_limeroad(search_term)
            listings += scrape_zobello(search_term)
            listings += scrape(search_term)
    else:
        listings = []

    context = {
        'listings': listings,
        'search': search_prod,
    }

    return render(request, 'dashboard.html', context)


def yellow(request):
    search_prod = ''
    search_term = ''
    if request.user.is_active:
        customer = request.user.customer
        search_color = 'yellow'
        search_prod = customer.favourite_item
        search_term = search_color + " " + search_prod
        search_term = request.user.customer.gender + ' ' + search_color + " " + search_prod
        print(search_term)
        if request.user.customer.gender == 'male':
            listings = scrape(search_term)
            listings += scrape_zobello(search_term)
            listings += scrape_limeroad(search_term)
        else:
            listings = scrape_limeroad(search_term)
            listings += scrape_zobello(search_term)
            listings += scrape(search_term)
    else:
        listings = []

    context = {
        'listings': listings,
        'search': search_prod,
    }

    return render(request, 'dashboard.html', context)


def white(request):
    search_prod = ''
    search_term = ''
    if request.user.is_active:

Dashboard/templates/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <title>Apna Dhukaan</title>
</head>

<body>

    <nav id="navbar" class="navbar custom-light navbar-expand-lg transparent navbar-inverse">

        <a class="navbar-brand ml-auto" href="{%url 'search:landing'%}">Apna Dhukaan</a>

        <button class="navbar-toggler navbar-light ml-auto" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
            aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'search:landing'%}">Home</a>
                </li>
                <li class="nav-item current">
                    <a class="nav-link" href="{% url 'search:limeroad' %}">Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'search:trending'%}">Trending</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'search:search-bewakoof' %}">Search By Term</a>
                </li>
            </ul>

        
            {% if user.is_authenticated %}
                <a href="{% url 'accounts:logout' %}" class="btn btn-primary glow-button" style="color: white">Log Out</a>
            {% else %}
                <a href="{% url 'accounts:login' %}" class="btn btn-primary glow-button" style="color: white">Login</a>
            {% endif %}
        
    </nav>

    {% block content %}

    {% endblock %}

    <!-- <script src="staticfiles/js/app.js"></script> -->

    <script type="text/javascript">

    /* Sticky Navbar */
    var nav = document.getElementById("navbar");
    var landing = document.getElementById("navbar-landing");
    var sticky;
    if(nav != null) sticky = nav.offsetTop;
    else sticky = landing.offsetTop;


    window.onscroll = () => {
        if (window.pageYOffset > sticky) {
            if(nav != null) nav.classList.add("sticky");
            else {
                landing.classList.add("sticky");
                landing.classList.add("custom-light");
                landing.classList.remove("custom-dark");
            }
        }
        else {
            if(nav != null) nav.classList.remove("sticky");
            else {
                landing.classList.remove("sticky");
                landing.classList.add("custom-dark");
                landing.classList.remove("custom-light");
            }
        }
    };

    /* Login Signup */
    function gotoSignUp() {
        document.getElementById("sign-up").style.display = "inline";
        document.getElementById("login").style.display = "none";
    }

    function gotoLogin() {
        document.getElementById("sign-up").style.display = "none";
        document.getElementById("login").style.display = "inline";
    }


    </script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>

Dashboard/templates/dashboard-product.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
    <div class="sidebar">
        <img class="profile" src="https://demos.creative-tim.com/bs3/material-kit-pro/assets/img/placeholder.jpg" alt="" height="80" width="80">
        {% if user.is_authenticated %}
            <p>Welcome, {{user.first_name | title}}!</p>
        {% else %}
            <p>Welcome, Stranger!</p>
        {% endif %}
        <a href="{% url 'Dashboard:dashboard' %}" class="">Recently Searched</a>
        {% if user.customer.favourite_color == 'red' %}
        <a href="{% url 'Dashboard:red' %}" class="">Recommendations</a>
        {% elif user.customer.favourite_color == 'blue' %}
        <a href="{% url 'Dashboard:blue' %}" class="">Recommendations</a>
        {% elif user.customer.favourite_color == 'green' %}
        <a href="{% url 'Dashboard:green' %}" class="">Recommendations</a>
        {% elif user.customer.favourite_color == 'black' %}
        <a href="{% url 'Dashboard:shorts' %}" class="">Recommendations</a>
        {% elif user.customer.favourite_color == 'white' %}
        <a href="{% url 'Dashboard:white' %}" class="">Recommendations</a>
        {% elif user.customer.favourite_color == 'yellow' %}
        <a href="{% url 'Dashboard:yellow' %}" class="">Recommendations</a>
        {%endif%}
        <a href="#" class="active">Suggestions</a>
    </div>

    {% if not user.is_authenticated %}
    <div class="content">
        <h2>Please Login to get Recommendations</h2>
    </div>
    {% else %}

    <div class="content">
        <h2>You might also like!</h2>
        <hr>
        <div class="info-message">
            {% if search %}
            We Know Your Choice Of Clothing is {{ search | title}}. Choose Your Color.
            {% else %}
            We Know Your Choice Of Clothing is {{ user.customer.favourite_color | title}}. Choose Your Product.
            {% endif %}
        </div>
        <div class="colour-select">
            <a href="{% url 'Dashboard:shirt' %}"><button class="rec-colors" style="background-color: white; font-weight: bolder;">Shirt</button></a>
            <a href="{% url 'Dashboard:jeans' %}"><button class="rec-colors" style="background-color: white; font-weight: bolder;">Jeans</button></a>
            <a href="{% url 'Dashboard:shorts' %}"><button class="rec-colors" style="background-color: white; font-weight: bolder;">Shorts</button></a>
            <a href="{% url 'Dashboard:shoes' %}"><button class="rec-colors" style="background-color:white; font-weight: bolder;">Shoes</button></a>
            <ion-icon name="sync-circle-outline" size="large" style="margin-top: 10px;"></ion-icon>
        </div>
        <hr>
        <div class="products-found">
            <!-- Insert product cards here! -->
            {% if listings %}
            {% for post in listings %}
            <div class="card" style="width: 18rem">
                <img src="{{ post.2 }}" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{post.0}}</h5>
                    <div class="container">
                        <h5>{{ post.1 }}</h5>
                        <a href="{{ post.3 }}" class="btn btn-primary glow-button">Visit Store</a>
                    </div>

                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    {% endif %}
{% endblock %}

Dashboard/templates/dashboard-recent.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
    <div class="sidebar">
        <img class="profile" src="https://demos.creative-tim.com/bs3/material-kit-pro/assets/img/placeholder.jpg" alt="" height="80" width="80">
        {% if user.is_authenticated %}
            <p>Welcome, {{user.first_name | title}}!</p>
        {% else %}
            <p>Welcome, Stranger!</p>
        {% endif %}
        <a href="#" class="active">Recently Searched</a>
        
        {% if user.customer.favourite_color == 'red' %}
        <a href="{% url 'Dashboard:red' %}" class="">Recommendations</a>
        {% elif user.customer.favourite_color == 'blue' %}
        <a href="{% url 'Dashboard:blue' %}" class="">Recommendations</a>
        {% elif user.customer.favourite_color == 'green' %}
        <a href="{% url 'Dashboard:green' %}" class="">Recommendations</a>
        {% elif user.customer.favourite_color == 'black' %}
        <a href="{% url 'Dashboard:black' %}" class="">Recommendations</a>
        {% elif user.customer.favourite_color == 'white' %}
        <a href="{% url 'Dashboard:white' %}" class="">Recommendations</a>
        {% elif user.customer.favourite_color == 'yellow' %}
        <a href="{% url 'Dashboard:yellow' %}" class="">Recommendations</a>
        {%endif%}

        <a href="{% url 'Dashboard:sugessions' %}" class="">Suggestions</a>
    </div>

    <div class="content">
        <h2>Recent Searches</h2>
        <hr>
        <div class="product-name">
            <a href="#">
                {{search1 | title}}
                <ion-icon name="arrow-forward-circle-outline"></ion-icon>
            </a>

        </div>
        {% if not user.is_authenticated %}
            <h2>Login To View Dashboard</h2>
        {% else %}

        <div class="products-found">
            <!-- Insert product cards here! -->
            {% if listings1 %}
            {% for post in listings1 %}
            <div class="card" style="width: 18rem">
                <img src="{{ post.2 }}" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{post.0}}</h5>
                    <div class="container">
                        <h5>{{ post.1 }}</h5>
                        <a href="{{ post.3 }}" class="btn btn-primary glow-button">Visit Store</a>
                    </div>

                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>

        <br>
        <div class="product-name">
            <a href="#">
                {{search2 | title}}
                <ion-icon name="arrow-forward-circle-outline"></ion-icon>
            </a>
        </div>
        <div class="products-found">
            <!-- Insert product cards here! -->
            {% if listings2 %}
            {% for post in listings2 %}
            <div class="card" style="width: 18rem">
                <img src="{{ post.2 }}" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{post.0}}</h5>
                    <div class="container">
                        <h5>{{ post.1 }}</h5>
                        <a href="{{ post.3 }}" class="btn btn-primary glow-button">Visit Store</a>
                    </div>

                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>

        <br>
        <div class="product-name">
            <a href="#">
                {{search3 | title}}
                <ion-icon name="arrow-forward-circle-outline"></ion-icon>
            </a>
        </div>
        <div class="products-found">
            <!-- Insert product cards here! -->
            {% if listings2 %}
            {% for post in listings3 %}
            <div class="card" style="width: 18rem">
                <img src="{{ post.2 }}" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{post.0}}</h5>
                    <div class="container">
                        <h5>{{ post.1 }}</h5>
                        <a href="{{ post.3 }}" class="btn btn-primary glow-button">Visit Store</a>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    {% endif %}

{% endblock %}

Dashboard/templates/dashboard-temp.html
{% extends 'base2.html' %}

{% load static %}



{% block content  %}
{% if not user.is_authenticated %}
<h1 class="text-center mt-5">Please Login To Acess Dashboard</h1>
{% else %}
<h1 class="text-center mt-5">Previously Searched</h1>
<h2 class="text-center mt-5">{{ search }}</h2>
{% endif %}
        {% if listings %}
        <div class="container products-found">
            <!-- Insert product cards here! -->
            {% for post in listings %}
            <div class="card" style="width: 18rem">
                <img src="{{ post.2 }}" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{ post.0 }}</h5>
                    <div class="container">
                        <h5>{{ post.1 }}</h5>
                        <a href="{{ post.3 }}" class="btn btn-primary glow-button" target="_blank">Visit Store</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
{% endblock %}

Dashboard/templates/dashboard.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
    <div class="sidebar">
        <img class="profile" src="https://demos.creative-tim.com/bs3/material-kit-pro/assets/img/placeholder.jpg" alt="" height="80" width="80">
        {% if user.is_authenticated %}
            <p>Welcome, {{user.first_name | title}}!</p>
        {% else %}
            <p>Welcome, Stranger!</p>
        {% endif %}
        <a href="{% url 'Dashboard:dashboard' %}" class="">Recently Searched</a>
        <a href="#" class="active">Recommendations</a>
        <a href="{% url 'Dashboard:sugessions' %}" class="">Suggestions</a>
    </div>

    {% if not user.is_authenticated %}
    <div class="content">
        <h2>Please Login to get Recommendations</h2>
    </div>
    {% else %}

    <div class="content">
        <h2>You might also like!</h2>
        <hr>
        <div class="info-message">
            We Know Your Choice Of Clothing is {{search | title}}. Choose Your Color.
        </div>
        <div class="colour-select">
            <a href="{% url 'Dashboard:yellow' %}"><button class="rec-colors" style="background-color: yellow;"></button></a>
            <a href="{% url 'Dashboard:red' %}"><button class="rec-colors" style="background-color: red;"></button></a>
            <a href="{% url 'Dashboard:green' %}"><button class="rec-colors" style="background-color: greenyellow;"></button></a>
            <a href="{% url 'Dashboard:white' %}"><button class="rec-colors" style="background-color:white; border-style: solid; border-width: thin; border-color: black;"></button></a>
            <a href="{% url 'Dashboard:blue' %}"><button class="rec-colors" style="background-color: blue;"></button></a>
            <a href="{% url 'Dashboard:black' %}"><button class="rec-colors" style="background-color: black;"></button></a>
            <ion-icon name="sync-circle-outline" size="large" style="margin-top: 10px;"></ion-icon>
        </div>
        <hr>
        <div class="products-found">
            <!-- Insert product cards here! -->
            {% if listings %}
            {% for post in listings %}
            <div class="card" style="width: 18rem">
                <img src="{{ post.2 }}" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{post.0}}</h5>
                    <div class="container">
                        <h5>{{ post.1 }}</h5>
                        <a href="{{ post.3 }}" class="btn btn-primary glow-button">Visit Store</a>
                    </div>

                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    {% endif %}
{% endblock %}